# 生信教程文章集锦 {#references}

## 生信宝典

生信的作用越来越大，想学的人越来越多，不管是为了以后发展，还是为了解决眼下的问题。但生信学习不是一朝一夕就可以完成的事情，也许你可以很短时间学会一个交互式软件的操作，却不能看完程序教学视频后就直接写程序。也许你可以跟着一个测序分析流程完成操作，但不懂得背后的原理，不知道什么参数需要修改，结果可以出来，却把我不住对还是错。

学习生信从来就不是一个简单的事，需要做好持久战的心理准备。

在学习时，我们都希望由浅入深的逐步深入，不断地练习和实践，这就是为什么我们需要一本书，因为书很系统。但生信发展的历史短于计算机编程的历史，如果想要一门程序设计的入门数据，每种语言都可以找到几本。但想要一个囊括生信的书，就有些难了。本身生信跨领域，需要多学科的知识，而其内部又有不少分子，都囊括了太大，包括的少又有些隔靴搔痒的感觉。

我们当时都是零基础下自学Linux,  自学Python，自学R，自学高通量测序；这些学习经历，之前都零星地记录在博客里。现在回头去看几年前自己记录的东西，觉得好简单，而当时却费了很大的力气。这些零星的随手记，当时也只是为了自己看，到现在确实只有自己能看得懂，不便惠及更多的人。

因此我们创建了生信宝典，希望从不同的角度传播知识。这个不同有三点含义，一是形式上的不同，摒弃之前主编们单人作战想写啥就写啥，而是有组织有计划的内容聚合，提供一系列的教程，由入门到提高。二是内容的不同，不去用网上现有教程的通用数据做例子，而是拿实际生物数据，讲述如何解释生信中普遍碰到的问题，讲述如何处理自己的数据。三是立足点不同。在写作时，我们回到了当年，在回忆中用整个阶段的学习去指导当初的那个小白，从那些会了的人觉得微不足道而不会的人又迈不过的坎入手，直击痛点。知识点的收录依据不是是否炫酷，是否难，而是是否必要。如果必要，再简单，也要提及；如果不必要，再炫酷，也暂不纳入。

通过大量的生信例子、关键的注释和浓缩的语句形成下面的一系列学习教程。每一篇内容都不多，可以当做小说阅读，也可以跟着去练，反复几遍，每读一次都会有不同的收获和体会。

### 系列教程

* [生物信息之程序](http://mp.weixin.qq.com/s/xoLBg0pI9seEksa0hMXi0A)
* [如何优雅的提问](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483955&amp;idx=1&amp;sn=946438376f94af6e8861b2b42701914e&amp;chksm=ec0dc7b9db7a4eafbef28fac1fb260f6f876f0ba674828784ac827dd23f9317f5a2d59d38bc0#rd)
* [生信宝典视频教程](http://mp.weixin.qq.com/s/C4EBufEtFF6bhBKrH8NXng)
* [好色之旅-画图三字经](https://mp.weixin.qq.com/s/bsvB1k17Izom2ldgdwXrdg)
* [转录组分析的正确姿势](http://mp.weixin.qq.com/s/Kx0gaU2x4pWjBq2I2Ffe6Q)
* [生信的系列教程](https://mp.weixin.qq.com/s/VguRtaGpEcaNzmZEi48gLg)
* [生信的系列书籍](http://mp.weixin.qq.com/s/IiehgNu3JGVTDa079ll1SQ)
* [文章用图的修改和排版 (1)](https://mp.weixin.qq.com/s/IJNyhinakY0lSXgCN7b9ug)
* [文章用图的修改和排版 (2)](http://mp.weixin.qq.com/s/HTsufk71U3wf14OOWSKEeQ)
* [简单强大的在线绘图](http://mp.weixin.qq.com/s/Ld2dNcaWR-jIzolHw_tkHA)
* [简单强大的在线绘图-升级版](http://mp.weixin.qq.com/s/pTHHqxuf0y1MCCCBaZjt9A)
* [论文图表基本规范](http://mp.weixin.qq.com/s/SCT4oso_vI0UNIJZTaG95g)
* [学术图表的基本配色方法](http://mp.weixin.qq.com/s/hq5p8Lqzn9Km2qVRLW2dVQ)
* [英语写作常见错误总结和学习视频](https://mp.weixin.qq.com/s/37dMnfA6RTSybzkzKnambw)
* [教育部推出首批490门“国家精品在线开放课程](http://mp.weixin.qq.com/s/JKn4kRiXYz6RKzQbTMVYlg)

### NGS分析工具评估

* [39个转录组分析工具，120种组合评估(转录组分析工具哪家强-导读版)](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&mid=2247484106&idx=1&sn=687a0def51f6ea91a335754eb3dc9ca9&chksm=ec0dc740db7a4e564e5b1e93a36e5d9447581e262eec9c2983d1d4e76788d673c9c07dec8f8e#rd)
* [39个转录组分析工具，120种组合评估(转录组分析工具大比拼 （完整翻译版）)](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&mid=2247484106&idx=2&sn=a09fa127d625c4072ae0343795346c56&chksm=ec0dc740db7a4e56821f32f60700027c85db46e81089721d1bbe23ceefa86160d9661c2f2d4c#rd)
* [无参转录组分析工具评估和流程展示](http://mp.weixin.qq.com/s/4HANWJY4oL7jGziroHfEpQ)

### 宏基因组教程

* [微生物组入门必读+宏基因组实操课程](http://mp.weixin.qq.com/s/sQyl5EctXFB95Oxg8YIasg)
* [扩增子图表解读-理解文章思路](http://mp.weixin.qq.com/s/oiVHO2S1JgYrKXPDU6fH2g)
* [扩增子分析流程-把握分析细节](http://mp.weixin.qq.com/s/KrYyy3jjzAL0rQzVfV6h4A)
* [扩增子统计绘图-冲击高分文章](http://mp.weixin.qq.com/s/6tNePiaDsPPzEBZjiCXIRg)
* [宏基因组分析教程](http://mp.weixin.qq.com/s/bcyvhFrNr6niqD13rQfZeg)
* [4500元的微生物组培训资料](http://mp.weixin.qq.com/s/li7SdZVaCEyFQF8h6MMh2A)

### 系列宣传

* [转录组分析的正确姿势](http://mp.weixin.qq.com/s/Kx0gaU2x4pWjBq2I2Ffe6Q)
* [120分的转录组考题，你能得多少](http://mp.weixin.qq.com/s/BmtIOcIzIutufFilbJIgEA)
* [生物信息作图系列R、Cytoscape及图形排版和Python编程培训研讨班开课了](http://mp.weixin.qq.com/s/x-DInL34BbKUR-2UD2Ec3g)
* [维密摔倒不可怕，关键时有人搀一把，坚持走下去](http://mp.weixin.qq.com/s/4mWms-r5kg8kN7kJ60zZDQ)
* [生物信息作图系列 - R、网络图及文章图形排版](http://mp.weixin.qq.com/s/IS3uVvulYsCbyuV64bcdLg)
* [易生信转录组培训总结和优惠分享](http://mp.weixin.qq.com/s/TLxzWyKImJhMINkNxLk6Yg)
* [生物信息9天速成班 — 你也可以成为团队不可或缺的人](http://mp.weixin.qq.com/s/aRuaX-qXlHkF2vme9QqWag)
* [Python没有捷径，但可以加速，零基础九天你也可以会编程](http://mp.weixin.qq.com/s/vDAHTitasAUphWsrS2Uzlg)
* [小学生都学Python了，你还不知道怎么开始-资源帖](http://mp.weixin.qq.com/s/1JlAROpOCBwaG574EwvkVw)
* [一个月学会Python的Quora指南和资料放送](http://mp.weixin.qq.com/s/VTVVfpNSGgOJLNxeIqmFiw)
* [扩增子分析基本流程和结果解读](http://mp.weixin.qq.com/s/cCW7HKjU8IetBgMoiYUeCQ)
* [微生物组——扩增子分析专题实战开课啦](http://mp.weixin.qq.com/s/y_KFJZlKSCJFmbuvNJQyAw)
* [如何入门生信Linux](http://mp.weixin.qq.com/s/V7vmnOv9rwKMoHtlPMo5nQ)
* [3分和30分文章差距在哪里？](https://mp.weixin.qq.com/s/kD-x7K4hI5KMgGXikyLt0Q)

### 生信生物知识

* [生物研究中不可缺少的数字概念，多少，多大，多快](http://mp.weixin.qq.com/s/JQBZv6snTkZzFwEG12riWw)

### 文献精读

* [CRISPR-CAS9发展历程小记](http://mp.weixin.qq.com/s/brx-i-Bbgp-XYwn5SkQLwA)
* [一场大病引起的诺贝尔2017年生理学奖角逐](http://mp.weixin.qq.com/s/T9Q6CUCt-wBoUCEwSBZALg)
* [Science搞反狗脑 - 人脑和狗脑一样？](https://mp.weixin.qq.com/s/zymhxusKNDZ9XynNGAlRcA)
* [一篇压根不存在的文献被引用400次？！揭开" 幽灵文献" 的真面目](http://mp.weixin.qq.com/s/OgAhb_UGUp7tZvQARbmLLg)
* [基于人工智能的文献检索，导师查找，更聪明](http://mp.weixin.qq.com/s/ikU0mVyX6BQNgljD1jCrRA)
* [GeenMedical：文献查询、筛选、引用排序、相似文献、全文下载、杂志分区、影响因子、结果导出、杂志评述、直接投稿，一站服务](http://mp.weixin.qq.com/s/hc8g64aHN7qv8YhVfrsuvQ)
* [YANDEX搜索，不翻墙稳定使用近谷歌搜索](http://mp.weixin.qq.com/s/fZ2Nm7Wck5mZLiESHcPusA)
* [Nature我的研究对后人毫无用途：21%的学术论文自发布后从未被引用](http://mp.weixin.qq.com/s/NMpqbKfXy002eMz9b9y1zg)
* [SCI-HUB镜像,  SSH隧道访问学校内网](https://mp.weixin.qq.com/s/NGsFlVb0fN1O37ecaYwxsA)
* [为了速成生物学，一位程序员探索了"爆款"基因背后的秘密](http://mp.weixin.qq.com/s/fFO6MX6Ttijx0bfYS5eQ-Q)

### Linux 

* [Linux-总目录](http://mp.weixin.qq.com/s/hEYU80fPf1eD5OWL3fO4Bg)
* [Linux-文件和目录](http://mp.weixin.qq.com/s/yKP1Kboji9N4p2Sl1Ovj0Q)
* [Linux-文件操作](http://mp.weixin.qq.com/s/4bYMzJclf_xHpqdrlbvAdA)
* [Linux文件内容操作](http://mp.weixin.qq.com/s/QFgINAYcQA9kYYSA28wK-Q)
* [Linux-环境变量和可执行属性](http://mp.weixin.qq.com/s/poFpNHQgHDr0qr2wqfVNdw)
* [Linux - 管道、标准输入输出](http://mp.weixin.qq.com/s/zL9Mw_2ig48gHrIjKM0CMw)
* [Linux - 命令运行监测和软件安装](http://mp.weixin.qq.com/s/TNU7X2mhfVVffaJ7NRBuNA)
* [Linux-常见错误和快捷操作](http://mp.weixin.qq.com/s/cDIN4_R4nETEB5irmIGFAQ)
* [Linux-文件列太多，很难识别想要的信息在哪列；别焦急，看这里。](http://mp.weixin.qq.com/s/1QaroFE7AH1pREuq-k2YAw)
* [Linux-文件排序和FASTA文件操作](http://mp.weixin.qq.com/s/R1OHRhZoDJuAdyVdJr2xHg)
* [Linux-应用Docker安装软件](http://mp.weixin.qq.com/s/HLHiWMLaWtB7SOJe_jP3mA)
* [Linux服务器数据定期同步和备份方式](http://mp.weixin.qq.com/s/c2cspK5b4sQScWYMBtG63g)
* [VIM的强大文本处理方法](https://mp.weixin.qq.com/s/4lUiZ60-aXLilRk9--iQhA)
* [Linux - Conda软件安装方法](http://mp.weixin.qq.com/s/A4_j8ZbyprMr1TT_wgisQQ)
* [查看服务器配置信息](http://mp.weixin.qq.com/s/xq0JfkHJJeHQk1acjOAJUQ)
* [Linux - SED操作，awk的姊妹篇](http://mp.weixin.qq.com/s/cywkIeRbhkYTZvkwTeIVSA)
* [Linux - 常用和不太常用的实用awk命令](http://mp.weixin.qq.com/s/8wD14FXt7fLDo1BjJyT0ew)
* [Bash概论 - Linux系列教程补充篇](http://mp.weixin.qq.com/s/lWNp_6W_jLiogmtlk9nO2A)

### CIRCOS系列

* [CIRCOS圈图绘制 - circos安装](http://mp.weixin.qq.com/s/OEBJU3BiQdQOeN_tD2o7sA)
* [CIRCOS圈图绘制 - 最简单绘图和解释](http://mp.weixin.qq.com/s/2E1Y5-cEdptkQGVm0bxKbQ)
* [CIRCOS圈图绘制 - 染色体信息展示和调整](https://mp.weixin.qq.com/s/o_3DyYdSubWCh5FfoVKBOg)
* [CIRCOS增加热图、点图、线图和区块属性](http://mp.weixin.qq.com/s/6L8wmsy0eOxtiAEs3hYgCA)

### R统计和作图

* [在R中赞扬下努力工作的你，奖励一份CheatShet](http://mp.weixin.qq.com/s/x3tWrQPriLRFXO8ZaD93EQ)
* [别人的电子书，你的电子书，都在bookdown](http://mp.weixin.qq.com/s/u8WfC4xQ562Uekhs4WVBoQ)
* [R语言 - 入门环境Rstudio](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483882&amp;idx=1&amp;sn=e16903b4b745a1ef51855be3824149f6&amp;chksm=ec0dc460db7a4d76a70bd4ca2d250f147225252ee963d3e577affaebeeb81dea1ff639d5e9aa#rd)
* [R语言 - 热图绘制 (heatmap)](http://mp.weixin.qq.com/s/mNSkf1rjWTCtE1pIOuI2rA)
* [R语言 - 基础概念和矩阵操作](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483891&amp;idx=1&amp;sn=40daf6435398c4d9a41f332e9bba4915&amp;chksm=ec0dc479db7a4d6fec413bfb90a4660eb035b440d2bbee998114f7af29e3b3338a8adf62540a#rd)
* [R语言 - 热图简化](https://mp.weixin.qq.com/s/_9LKs6t6rcjzokF_0gneSA)
* [R语言 - 热图美化](http://mp.weixin.qq.com/s/lKrhvYrwn93esC6MA3bHWw)
* [R语言 - 线图绘制](http://mp.weixin.qq.com/s/YB-9tE4ut9RN0yfS8qBhtQ)
* [R语言 - 线图一步法](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483947&amp;idx=1&amp;sn=7cf0252efff5433447507b977fcaff97&amp;chksm=ec0dc7a1db7a4eb77a269709bdf2c8ab51bcad89aa780ec0be171a333e1cb8f3cc27eff277a1#rd)
* [R语言 - 箱线图（小提琴图、抖动图、区域散点图）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483964&amp;idx=1&amp;sn=ee52ac37fb9a919f5c75c0abe2a49ad4&amp;chksm=ec0dc7b6db7a4ea0a51306347fc43265c41fda3eeaf4764ddc3795546371327579676cd74a38#rd)
* [R语言 - 箱线图一步法](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483971&amp;idx=1&amp;sn=1b40a1137ccb8b2fa1ab3eb1d0f05de9&amp;chksm=ec0dc7c9db7a4edf16ea4966b9acb7f23cd23bd6a2e59450ae11bdac899fa2fceb124264dcf4#rd)
* [R语言 - 火山图](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483996&amp;idx=1&amp;sn=9a29d52e78e9acffeb0a78077a14f9f2&amp;chksm=ec0dc7d6db7a4ec0163259e81e4ded54875a5dd8adaafbc6975a86c71223d863627ba37801e5#rd)
* [R语言 - 富集分析泡泡图 （文末有彩蛋）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483978&amp;idx=1&amp;sn=e0c158c0e92375553036cc37f4987e40&amp;chksm=ec0dc7c0db7a4ed6ac593493b7d8b52f11f2feb92d24fa00d19527fbb6f95b24f7e313ef9440#rd)
* [R语言 - 散点图绘制](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484056&amp;idx=1&amp;sn=f9b2b4f7495b432e9294b7cbf42eaf33&amp;chksm=ec0dc712db7a4e04769d322558364b4b401b0a8153097c7252e83170e9201a31c2a7abbaf101#rd)
* [一文看懂PCA主成分分析](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484036&amp;idx=1&amp;sn=22ee356d0c9680d56dada1b777985ed2&amp;chksm=ec0dc70edb7a4e182a21475e9ddcde35b907c291549cc8c2e767be260af445ff5455aa358b04#rd)
* [富集分析DotPlot，可以服](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484063&amp;idx=1&amp;sn=f4e93d428e4910b4abbee9c0430cd170&amp;chksm=ec0dc715db7a4e0318b388ba2ab3d51677741421c42ada474a0ac6046a0699283014eae84b6f#rd)
* [R语言 - 韦恩图](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&mid=2247484076&idx=1&sn=fa5af19a2a4db4b0c5c7f145bf93ca57&chksm=ec0dc726db7a4e30fe7a0492ed9ea8eb5fa1c34641b1442a2da003efde0546b30c48fde3f118#rd)
* [R语言 - 柱状图](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484134&amp;idx=1&amp;sn=ffb41298eae74834af2f5dad05d37921&amp;chksm=ec0dc76cdb7a4e7a852ac0670532c12c690399f140a2335f640eaf01f7da26bc5480941686a9#rd)
* [R语言 - 图形设置中英字体](http://mp.weixin.qq.com/s/NAwyvtTS7t5rRU7KKBwHTA)
* [R语言 - 非参数法生存分析](http://mp.weixin.qq.com/s/_Dy9Yn8fc8I0rASGxH5x9A)
* [基因共表达聚类分析和可视化](http://mp.weixin.qq.com/s/ST2SAmfKOptpJOHS8podmQ)
* [R中1010个热图绘制方法](http://mp.weixin.qq.com/s/N7oLvJ1oPIImgybJVVSxXg)
* [还在用PCA降维？快学学大牛最爱的t-SNE算法吧, 附Python/R代码](http://mp.weixin.qq.com/s/alBfj3Y08qCnZoz5JwVdaw)
* [一个函数抓取代谢组学权威数据库HMDB的所有表格数据](http://mp.weixin.qq.com/s/rYjcsfHrbcAhaFpQI5Yc6g)
* [文章用图的修改和排版](https://mp.weixin.qq.com/s/IJNyhinakY0lSXgCN7b9ug)
* [network3D: 交互式桑基图](http://mp.weixin.qq.com/s/3okqP0viU3EVML9p1bkQlw)
* [network3D 交互式网络生成](https://mp.weixin.qq.com/s/rK5SolI0xGisvBCIcb448A)

### 扩增子三步曲

* [1图表解读-理解文章思路](http://mp.weixin.qq.com/s/oiVHO2S1JgYrKXPDU6fH2g)  
* [2分析流程-把握分析细节](http://mp.weixin.qq.com/s/KrYyy3jjzAL0rQzVfV6h4A)  
* [扩展1：视频教程-夯实分析思路](http://mp.weixin.qq.com/s/SxWl0qBJgg8ziZUFDmKvpQ)  
* [扩展2：QIIME2教程-了解分析趋势](http://mp.weixin.qq.com/s/wkn-91BVOSWZLRvlcaaEgg)  
* [3统计绘图-冲击高分文章](http://mp.weixin.qq.com/s/6tNePiaDsPPzEBZjiCXIRg)  

### 宏基因组分析专题

* [1背景知识-Shell入门与本地blast实战](http://mp.weixin.qq.com/s/jASOBPzpwYCL-fWNUJJp8g)
* [2数据质控fastqc,  Trimmomatic,  MultiQC,  khmer](http://mp.weixin.qq.com/s/3O01eNMe79J_kUTaJjP6ag)
* [3组装拼接MEGAHIT和评估quast](http://mp.weixin.qq.com/s/NMKX0iDuR_qOzmLXxC8MEQ)
* [4基因注释Prokka](http://mp.weixin.qq.com/s/1TM61IrzrpVb5KhZ5A0kZQ)
* [5基于Kmer比较数据集sourmash](https://mp.weixin.qq.com/s/Rmx-z1zxj7GF9ivJGWVvLg)
* [6不比对快速估计基因丰度Salmon](http://mp.weixin.qq.com/s/2fwEtnEsBi5cJ65xyeoXxw)
* [7bwa序列比对,  samtools查看,  bedtools丰度统计](http://mp.weixin.qq.com/s/rdTFTFg0rZOIa2_tuFEOUA)
* [8分箱宏基因组binning,  MaxBin,  MetaBin,  VizBin](http://mp.weixin.qq.com/s/rZitcvykAlxnsNEzsW5JRg)
* [9组装assembly和分箱bin结果可视化—Anvio](http://mp.weixin.qq.com/s/FesH_mCunpZLpKC2pIg1UQ)
* [10绘制圈图-Circos安装与使用](http://mp.weixin.qq.com/s/FJlKY3kU5Fm6bYkjtwRkEw)
* [MetaPhlAn2分析有参宏基因组](http://mp.weixin.qq.com/s/xSjFGwcr1XIAZKdByJAWmQ)

### NGS基础

* [NGS基础 - FASTQ格式解释和质量评估](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484047&amp;idx=1&amp;sn=3e2a79d9f56040a57ac2e16cf1923b54&amp;chksm=ec0dc705db7a4e133e6e91de9ac11a6c0690f03d7b3b760b358e9b0d1a2d57974599419d9fff#rd)
* [NGS基础 - 高通量测序原理](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484034&amp;idx=1&amp;sn=e7680ee935f8603214227b37eeb2c567&amp;chksm=ec0dc708db7a4e1eca4e38845381f328c49c84a90ad6580c3ba3761511772636e5ec0f185931#rd)
* [NGS基础 - 参考基因组和基因注释文件](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484148&amp;idx=1&amp;sn=525233898721a9c3ebdf275babf14944&amp;chksm=ec0dc77edb7a4e686440e0cbe5fbf39f554c4183dc30e7870ab7584e285f4e018dd94b680f79#rd)
* [NGS基础 - GTF/GFF文件格式解读和转换](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484166&amp;idx=1&amp;sn=417e155672bd718def86003b16bf0078&amp;chksm=ec0dc68cdb7a4f9a6bcb62c18797a69040173e2b0af20f1cf87d3e0d75e3adee03c7ff524dc5#rd)
* [本地安装UCSC基因组浏览器](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484167&amp;idx=1&amp;sn=ef9699899164d23013d92b61331c6562&amp;chksm=ec0dc68ddb7a4f9bfb83b9942196622f8b8f52b041d3f4a12786e6464752fbeaf64c9a640e39#rd)
* [测序数据可视化 (一)](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483946&amp;idx=1&amp;sn=3f95769229f28a91ed8bf5889e2181be&amp;chksm=ec0dc7a0db7a4eb64d08c7799cfe698a1662e6d0d935a8b91c6c969aae86900df4decc469a0d#rd)
* [测序文章数据上传找哪里](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483843&amp;idx=1&amp;sn=43770d21f6c2da2393c31cd55fdbe31e&amp;chksm=ec0dc449db7a4d5f723842286bf7feab7830eba5d9778d351569810a069e5ace76040f94a6bd#rd)
* [GO、GSEA富集分析一网打进](http://mp.weixin.qq.com/s/d1KCETQZ88yaOLGwAtpWYg)
* [GSEA富集分析 - 界面操作](http://mp.weixin.qq.com/s/3Nd3urhfRGkw-F0LGZrlZQ)
* [去东方，最好用的在线GO富集分析工具](https://mp.weixin.qq.com/s/l6j2encDfEQkt2UeNCMFhg)
* [生信软件系列 - NCBI使用](http://mp.weixin.qq.com/s/4a5U8GdBoNFXkykL6m2EeA)

### 癌症数据库

* [UCSC XENA - 集大成者(TCGA, ICGC)](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484383&amp;idx=1&amp;sn=09c58de206f409fa375fb7af94d0084c&amp;chksm=ec0dc655db7a4f438cb7e53f281cb5c6bf2484619b3c72d7eafe064ea6a342f69587353531af#rd)
* [ICGC数据库使用](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484378&amp;idx=1&amp;sn=eb6a0f890326898b2fb0867c58f0cf90&amp;chksm=ec0dc650db7a4f46a0a265ec96b73f367d45f86318087507eef7dde117a369cb7ad427bebb1e#rd)
* [TCGA数据库在线使用](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484304&amp;idx=1&amp;sn=6ad44dafdc7613e33e13aac48edb32aa&amp;chksm=ec0dc61adb7a4f0c504f3aeb207132aef479572ea756ce15868cbc57f88e9ea25102752b646a#rd)
	
### Python

* [Python学习 - 可视化变量赋值、循环、程序运行过程](https://mp.weixin.qq.com/s/zhr251PCTDGBO1YxYB-P6Q)
* [Python极简教程 （一）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483866&amp;idx=1&amp;sn=310341a1c8d348958c304df03dfd06a0&amp;chksm=ec0dc450db7a4d46e369637cd2867b0e56389bf4f2e1d0dce409bba38882e61e5063308a13af#rd)
* [Python教程（二）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483866&amp;idx=2&amp;sn=bf3c07ee1b2936c7ea06b5d4ca820545&amp;chksm=ec0dc450db7a4d469f4f625babfb595b068137ea2b25a7682f9fb58ff771db6543f43def7950#rd)
* [Python教程（三）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483866&amp;idx=3&amp;sn=dec66c5f3f12919ce1b0bfbb545e3935&amp;chksm=ec0dc450db7a4d46e91b65446d6a192056ab6ff27c019fe3770cc32816b0ae3f16659ebba0a5#rd)
* [Python教程 （四）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483866&amp;idx=4&amp;sn=3a0b0c5c0f736ddeadc4524bae8b2a91&amp;chksm=ec0dc450db7a4d465602b74e0fa968519a3a085a1901b5cca97ff886163422a24089378ff8f0#rd)
* [Python教程（五）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483866&amp;idx=5&amp;sn=fd3526e11c4adf8194e1f92cd6d1749c&amp;chksm=ec0dc450db7a4d468c7d114352153eecbaedd7d37065f681caa28b74258a92038d1d2030056b#rd)
* [Python教程 （六）](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483866&amp;idx=6&amp;sn=ef7a0972abc002cfeba27815020e83aa&amp;chksm=ec0dc450db7a4d46f61328946fe257a1516785fb9a1f7c1663e86e4255ae6b616e3c07ac1cb0#rd)
* [Pandas，让Python像R一样处理数据，但快](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483865&amp;idx=1&amp;sn=a2e1474bbebce343ff4262e38653f4c4&amp;chksm=ec0dc453db7a4d45349076b1627eff5e292abceada59e832a46553f4ca614d62df96e097f871#rd)
* [Python解析psiBlast输出的JSON文件结果](http://mp.weixin.qq.com/s/BN6u2aJkoMzffPv7rvbm8g)
* [为啥我的Python这么慢 - 项查找 (二)](http://mp.weixin.qq.com/s/-0UTgmdRQbF7I4fib62ooA)
* [为啥我的Python这么慢 (一)](https://mp.weixin.qq.com/s/n5kkZfC8FGlzeBODarLHcw)
* [Python资源](http://mp.weixin.qq.com/s/1JlAROpOCBwaG574EwvkVw)
* [关于Python中的__main__和编程模板](http://mp.weixin.qq.com/s/JHDvdqq3Z-7uDmsyroblNQ)

### NGS软件

* [Rfam 12.0+本地使用 （最新版教程）](http://mp.weixin.qq.com/s/5OIRHA22ZLr5Z8bEhDiBqg)
* [轻松绘制各种Venn图](http://mp.weixin.qq.com/s/zn654JqG9OeO71rJUTDr2Q)
* [ETE构建、绘制进化树](http://mp.weixin.qq.com/s/DD1nZnx5mYxWGrohNgdPvQ)
* [psRobot：植物小RNA分析系统](http://mp.weixin.qq.com/s/kWkEQOX-6SKMAUQmAuc86w)
* [生信软件系列 - NCBI使用](http://mp.weixin.qq.com/s/4a5U8GdBoNFXkykL6m2EeA)
* [去东方，最好用的在线GO富集分析工具](https://mp.weixin.qq.com/s/l6j2encDfEQkt2UeNCMFhg)

### Cytoscape网络图

* [Cytoscape教程1](http://mp.weixin.qq.com/s/m9uJm8GwSXb3xaRxtod08Q)
* [Cytoscape之操作界面介绍](http://mp.weixin.qq.com/s/ZSoW7-qWs3BuSB7bkDnfmA)
* [新出炉的Cytoscape视频教程](http://mp.weixin.qq.com/s/sKEy_Pn9qnWw4W-aXraA5g)

### 分子对接

* [来一场蛋白和小分子的风花雪月](http://mp.weixin.qq.com/s/asAJDttAvsCLGd3PPU2agQ)
* [不是原配也可以-对接非原生配体](http://mp.weixin.qq.com/s/VDN1qAZGIMol6prwQW4umw)
* [简单可视化-送你一双发现美的眼睛](http://mp.weixin.qq.com/s/P62sjqhSTxmWVicrEAk-RQ)
* [你需要知道的那些前奏](http://mp.weixin.qq.com/s/5a5-6pXHfvyDc2Kfp4xDeQ)

### 生信宝典之傻瓜式

* [生信宝典之傻瓜式 (一) 如何提取指定位置的基因组序列](http://mp.weixin.qq.com/s/5bNdHkl3QDFmCNmrht3VWA)
* [生信宝典之傻瓜式 (二) 如何快速查找指定基因的调控网络](http://mp.weixin.qq.com/s/LPWaxbKuS-XlvzkSE-MupQ)
* [生信宝典之傻瓜式 (三) 我的基因在哪里发光 - 如何查找基因在发表研究中的表达](http://mp.weixin.qq.com/s/0Yvhn5Tlb-zvOXM0cU16Zg)
* [生信宝典之傻瓜式 (四) 蛋白蛋白互作网络在线搜索](http://mp.weixin.qq.com/s/JO1J66BtzuY-9a20x0XQcg)
* [生信宝典之傻瓜式 (五) 文献挖掘查找指定基因调控网络](http://mp.weixin.qq.com/s/DQ4fjCL777D2iEcPTnd-rA)

### 生信人写程序

* [生信人写程序1. Perl语言模板及配置](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483837&amp;idx=1&amp;sn=660358a38b7fa6d3de2c95280f7a4535&amp;chksm=ec0dc437db7a4d21368b312ac43ceae552e1544570639c949e96bf488113a55f67fa2306008e#rd)
* [生信人写程序2. Editplus添加Perl, Shell, R, markdown模板和语法高亮](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247483910&amp;idx=1&amp;sn=7813eaa4841d90b0bfc3982bb901de81&amp;chksm=ec0dc78cdb7a4e9a866f3e0cade3096a13366cac18c873820434f066fdba9bd22a7b5b3d210d#rd)

### 小技巧系列

* [参考文献中杂志名字格式混乱问题一次解决](http://mp.weixin.qq.com/s/Diwevx-TVe0Vq_rdgzIkrw)

### 招聘

* [易汉博欢迎您加入](http://mp.weixin.qq.com/s?__biz=MzI5MTcwNjA4NQ==&amp;mid=2247484036&amp;idx=5&amp;sn=bb1007d2c3d60e7a2bcf2d6fc7a9a2bb&amp;chksm=ec0dc70edb7a4e185bafd0f49440bf1a032915c7e8d8fc2cb37c70a81ce3446a4ae990df89a5#rd)

## 宏基因组

<http://mp.weixin.qq.com/s/5jQspEvH5_4Xmart22gjMA>

宏基因组/微生物组是当今世界科研最热门的研究领域之一，为加强本领域的技术交流与传播，推动中国微生物组计划发展，中科院青年科研人员创立“宏基因组”公众号，目标为打造本领域纯干货技术及思想交流平台。

本公众号每日推送，工作日分享宏基因组领域科研思路、实验和分析技术，理论过硬实战强；周末科普和生活专栏，轻松读文看片涨姿势。目前经过近半年发展，分享过百篇原创文章，已有14000+小伙伴在这里一起交流学习，感兴趣的赶快关注吧。

### 精选文章推荐

**5000+**

- [微生物组入门必读+宏基因组实操课程](http://mp.weixin.qq.com/s/sQyl5EctXFB95Oxg8YIasg)
- [你想要的生信知识全在这—生信宝典](http://mp.weixin.qq.com/s/2b3_8Vvv7McqCkEfUszW3A)
- [生物信息9天速成班—成为团队不可或缺的人](http://mp.weixin.qq.com/s/1nf7vwyvC3oemkTq_pu87A)
- [3分和30分文章差距在哪里？](http://mp.weixin.qq.com/s/kD-x7K4hI5KMgGXikyLt0Q)
- [肠道菌群在人体中的作用](http://mp.weixin.qq.com/s/3T768LA6MWujF4yuzK4MKQ)
- [看完此片我想把身上的细菌寄生虫供起来](http://mp.weixin.qq.com/s/_DUI6tOYTEq0Wu7K7iRTxw)
- [岛国科普—生命大跃进](http://mp.weixin.qq.com/s/O_0Il0G_v_aSwkUH_noZVA)
- [我们的未来在哪里？](https://mp.weixin.qq.com/s/l141ggt2c-h7Eymc0UQnfQ)
- [论文图表基本规范](http://mp.weixin.qq.com/s/SCT4oso_vI0UNIJZTaG95g)
- [DNA提取发Nature](http://mp.weixin.qq.com/s/lO5uiMjixJ6aYTjPX-IyaQ)
- [实验vs数据分析，谁对结果影响大?](http://mp.weixin.qq.com/s/cL_IAoPFfmelKMPMgltrfA)

**3000+**

- [扩增子图表解读-理解文章思路](http://mp.weixin.qq.com/s/oiVHO2S1JgYrKXPDU6fH2g)
- [扩增子分析流程-把握分析细节](http://mp.weixin.qq.com/s/KrYyy3jjzAL0rQzVfV6h4A)
- [扩增子统计绘图-冲击高分文章](http://mp.weixin.qq.com/s/6tNePiaDsPPzEBZjiCXIRg)
- [宏基因组分析教程](http://mp.weixin.qq.com/s/bcyvhFrNr6niqD13rQfZeg)
- [4500元的微生物组培训资料](http://mp.weixin.qq.com/s/li7SdZVaCEyFQF8h6MMh2A)
- [Co-occurrence网络图在R中的实现](http://mp.weixin.qq.com/s/s-Si_s5pk7EF5gueqruBRQ)
- [学术图表的基本配色方法](http://mp.weixin.qq.com/s/hq5p8Lqzn9Km2qVRLW2dVQ)
- [一文读懂进化树](https://mp.weixin.qq.com/s/GV8rU3FZdc8Y-x931k_yrQ)
- [自学生信-biostar handbook](http://mp.weixin.qq.com/s/JL-n2nD6YL8vwuRtTVmQlQ)
- [漱口水增加糖尿病，高血压风险](http://mp.weixin.qq.com/s/NxNcDljhyvubbYzVgggHfw)

**1000+**

- [微生物组——扩增子分析专题培训开课啦！！！](http://mp.weixin.qq.com/s/xxBC2VMpB7uz_rJFBSb5mQ)
- [最简单漂亮的免费在线生信绘图工具](http://mp.weixin.qq.com/s/O0QAQyfxnrXlFLw268B7lg)
- [小学生都学Python了，你还不知道怎么开始](http://mp.weixin.qq.com/s/RaxOgjq4hyr-RNGSB-RGzg)
- [五彩进化树与热图更配-ggtree美颜进化树](http://mp.weixin.qq.com/s/yWzFAS8Nk6fpTuAJzbG6nA)
- [扩增子分析还聚OTU就真OUT了](http://mp.weixin.qq.com/s/D3qKT7mYEg52nCfQWF75wg)
- [主流非聚类方法dada2,deblur和unoise3介绍与比较](http://mp.weixin.qq.com/s/hU4AavhMQcebNhBtMUg1tw)
- 16S预测微生物群落功能 [0概述](http://mp.weixin.qq.com/s/sztbvfdf9wa-3HJXc_m8TQ)   [1KO通路PICRUSt](https://mp.weixin.qq.com/s/LWtiwBbUCAadMZPaKKDMag)  [2元素循环FAPROTAX](http://mp.weixin.qq.com/s/J8EwJD_PTDhqRaD7kXlK1A)  [3表型bugbase](https://mp.weixin.qq.com/s/1WdysPZWo0H6NSYiNpcMUQ) [4KO通路Tax4Fun](http://mp.weixin.qq.com/s/dzsh44ue93xnAs7gTde7wg)  
- [一文读懂微生物组](https://mp.weixin.qq.com/s/KT4hJFbJFnGPQQYgQUd8fg)
- [2017年发展简史和十大热文盘点](https://mp.weixin.qq.com/s/9sUOcZTsfOXBjj03OHGy6Q)

### 培训、会议、征稿、招聘

- [3月10-19日，北京，微生物组——扩增子分析专题培训](http://mp.weixin.qq.com/s/xxBC2VMpB7uz_rJFBSb5mQ)
- [5月11-13日，北京，中国肠道大会](http://mp.weixin.qq.com/s/b_ron-vL6n-0CDJW87l2rQ)

### 科研经验

- [如何优雅的提问](http://mp.weixin.qq.com/s/H9gkepap0hy3NNskOkO44w)
- [公众号搜索方法大全](http://mp.weixin.qq.com/s/wn2bqIPgT5UD-GP1qzkJFA)
- **科研团队成长三部曲**：[1云笔记](http://mp.weixin.qq.com/s/OnwhWlq3cTycf-W1rxgV7g) [2云协作](http://mp.weixin.qq.com/s/W5By9mZ5PI57_xFfZ_JXiw) [3公众号](http://mp.weixin.qq.com/s/hd0sdBDAMqMJsXQs0pIjUg)
- 文献阅读 [1热心肠](http://mp.weixin.qq.com/s/1uBeAQ0utxuzTTtfUx_UXA) [2SemanticScholar](https://mp.weixin.qq.com/s/gaQiUrRqLpfTXzjyfbua6A) [3geenmedical](https://mp.weixin.qq.com/s/hc8g64aHN7qv8YhVfrsuvQ)
- 生信编程模板 [Perl](http://mp.weixin.qq.com/s/u2ZmTo-z6cbN-L6KVLYNwg)  [Shell](http://mp.weixin.qq.com/s/YevGR79NnBAF-xtrqL8gAA)  [R](http://mp.weixin.qq.com/s/OQiE882jM6pVwqTiIjyZ1Q)
- [生物信息之程序学习](http://mp.weixin.qq.com/s/xoLBg0pI9seEksa0hMXi0A)  
- [Endnote X8云同步：有网随时读文献](http://mp.weixin.qq.com/s/SPblPs5ByPdb2C400kIK3w)
- [论文Figures，你不能不知道的秘密](http://mp.weixin.qq.com/s/UQtKZ14_6WTyFYGZgiC00g)
- [转录组分析的正确姿势](http://mp.weixin.qq.com/s/sTzluM0EMNYLnwYa5JaKLg)
- [整个世界都是你的已知条件](http://mp.weixin.qq.com/s/9Sj5tI8RRa3uv2BgNarhxw)

### 软件和数据库使用

- SILVAngs:16S/18S在线分析[1](http://mp.weixin.qq.com/s/R4fzOl1JX097rxi18vfePw)  [2](http://mp.weixin.qq.com/s/2mv_w-RG50v54iojii7kuA)
- [METAGENassist帮你搞定宏基因分析的所有图形需求](http://mp.weixin.qq.com/s/kVrMGI8mtkJkltCpAbwUiw)
- [Windows不用虚拟机或双系统，轻松实现linux shell环境：gitforwindows](http://mp.weixin.qq.com/s/GYa5_0bcZO6Pfq-qim5vyA)
- [一条命令轻松绘制CNS顶级配图-ggpubr](http://mp.weixin.qq.com/s/EvlnWBI5OZOudWd0cieGJg)
- [ggbiplot-最好看的PCA图](http://mp.weixin.qq.com/s/GGCPxQEe_DXefdp-veQtag)
- [LDA分析、作图及添加置信-ggord](https://mp.weixin.qq.com/s/F9c_ISpOpjHyiCNahoYTqQ)
- [ggrepel-解决散点图样品标签重叠，方便筛选样品](http://mp.weixin.qq.com/s/hxBAlnK_1ZSGJQg1mwsssw)
- [Alpha多样性稀释曲线rarefraction curve](http://mp.weixin.qq.com/s/pQluUR7MYSZCheqVvAaNWA)
- [微生物组间差异分析神器-STAMP](http://mp.weixin.qq.com/s/f02mPAXCobPQijkIis-c2w)  
- [扩增子分析神器USEARCH](http://mp.weixin.qq.com/s/oJDfShs7gXCkOzYfa_winQ)
- [微生物扩增子数据库大全](http://mp.weixin.qq.com/s/DL7e6ihq6QppyW-87COiBg)  
- [antiSMASH：微生物次生代谢物基因簇预测](http://mp.weixin.qq.com/s/0MkmAw7f8uVQihrbUA2Z9Q)  
- [微生物网络构建：MENA, LSA, SparCC和CoNet](http://mp.weixin.qq.com/s/YPZar_aDmKE4W9s45NvhgQ)  
- [Cytoscape: MCODE增强包的网络模块化分析](https://mp.weixin.qq.com/s/jGHuP1ikCX0n3vKfS3VXPQ)
- [FUNGuild：真菌功能注释](http://mp.weixin.qq.com/s/pO3VCMLwEFLlcEgMQsUjDg) 
- [在线RaxML构建系统发育树](http://mp.weixin.qq.com/s/AWfT2szILVrCr25g0EdgvA)
- [Genevestigator: 查找基因在发表研究中的表达](https://mp.weixin.qq.com/s/mHBH-ooJ9vBpv0nvRFuF3A)
- [psRobot：植物小RNA分析系统](http://mp.weixin.qq.com/s/drpMN55hfbVwHbLYXC0oUw)  
- [RepeatMasker：基因组重复序列注释](http://mp.weixin.qq.com/s/vVamtB4mBAauqjpEFBg70A)  

### 扩增子学习三步曲

#### [1图表解读-理解文章思路](http://mp.weixin.qq.com/s/oiVHO2S1JgYrKXPDU6fH2g)  

#### [2分析流程-把握分析细节](http://mp.weixin.qq.com/s/KrYyy3jjzAL0rQzVfV6h4A)  

- [扩展1：视频教程-夯实分析思路](http://mp.weixin.qq.com/s/SxWl0qBJgg8ziZUFDmKvpQ)  
- [扩展2：QIIME2教程-了解分析趋势](http://mp.weixin.qq.com/s/wkn-91BVOSWZLRvlcaaEgg)  

#### [3统计绘图-冲击高分文章](http://mp.weixin.qq.com/s/6tNePiaDsPPzEBZjiCXIRg)  

### 宏基因组分析专题

- [1背景知识-Shell入门与本地blast实战](http://mp.weixin.qq.com/s/jASOBPzpwYCL-fWNUJJp8g)
- [2数据质控fastqc, Trimmomatic, MultiQC, khmer](http://mp.weixin.qq.com/s/3O01eNMe79J_kUTaJjP6ag)
- [3组装拼接MEGAHIT和评估quast](http://mp.weixin.qq.com/s/NMKX0iDuR_qOzmLXxC8MEQ)
- [4基因注释Prokka](http://mp.weixin.qq.com/s/1TM61IrzrpVb5KhZ5A0kZQ)
- [5基于Kmer比较数据集sourmash](https://mp.weixin.qq.com/s/Rmx-z1zxj7GF9ivJGWVvLg)
- [6不比对快速估计基因丰度Salmon](http://mp.weixin.qq.com/s/2fwEtnEsBi5cJ65xyeoXxw)
- [7bwa序列比对, samtools查看, bedtools丰度统计](http://mp.weixin.qq.com/s/rdTFTFg0rZOIa2_tuFEOUA)
- [8分箱宏基因组binning, MaxBin, MetaBin, VizBin](http://mp.weixin.qq.com/s/rZitcvykAlxnsNEzsW5JRg)
- [9组装assembly和分箱bin结果可视化—Anvi'o](http://mp.weixin.qq.com/s/FesH_mCunpZLpKC2pIg1UQ)
- [10绘制圈图-Circos安装与使用](http://mp.weixin.qq.com/s/FJlKY3kU5Fm6bYkjtwRkEw)
- [MetaPhlAn2分析有参宏基因组](http://mp.weixin.qq.com/s/xSjFGwcr1XIAZKdByJAWmQ)

### R统计绘图

- [视频教程：R语言recharts包绘制交互式图形](http://mp.weixin.qq.com/s/XOZD4ftYLPZjM2IVLYgUpA)
- [R语言聚类分析--cluster, factoextra](https://mp.weixin.qq.com/s/9EChqbVmFrNWi_Siu4hdqQ)
- [堆叠柱状图各成分连线画法：突出展示组间物种丰度变化](https://mp.weixin.qq.com/s/FZWinr14RTs6YSUE_juaug)
- [R相关矩阵可视化包ggcorrplot](http://mp.weixin.qq.com/s/AEfPqWO3S0mRnDZ_Ws9fnw)

### 实验设计与技术

- [微生物样本取样及微生物基因组DNA提取建议](http://mp.weixin.qq.com/s/L1XxsGDFt9wKk-4pSRwUUQ)
- 样品生物学重复数据选择 [1必要性](https://mp.weixin.qq.com/s/_qqeKbncKZmovajvPbskpA)  [2需要多少重复？](http://mp.weixin.qq.com/s/_qqeKbncKZmovajvPbskpA)
- 样品命名 [注意事项](http://mp.weixin.qq.com/s/3-UlDWEwCvU5TUlu-_ezmg)
- 扩增子引物选择 [16S结构](http://mp.weixin.qq.com/s/pBzh1LcdEy-EJop44z0mwA) [16S单V4区是最佳选择?](http://mp.weixin.qq.com/s/hMlfNQmXkt8o-ew_iSV30Q)
- [海洋可培养微生物的鉴定与分类](http://mp.weixin.qq.com/s/-0eqsE5slOyEcXFfjY7NNw)
- [怎么取粪便样品](http://mp.weixin.qq.com/s/fHwd2pc-E314JO_Ya4QEvQ)
- [Rhizosphere、Rhizoplane根际土如何取](http://mp.weixin.qq.com/s/6hOd-NV1TNXGQdxL0k9l0g)
- [Nat. Biotechnol.扩增子测序革命—用16S及18S rRNA全长进行微生物多样性研究](http://mp.weixin.qq.com/s/vUtQmuj1vIoH9L0J-YT5fQ)

### 基础知识

- [Microbiota, metagenome, microbiome区别](http://mp.weixin.qq.com/s/kBbWD6ircc4UHE-ma-6a1Q)
- [16S测序，不知道OTU你就out了！](http://mp.weixin.qq.com/s/yDmUgRzgJDtxdiJqwpGM1A)
- [计量宏基因组学数据分析的方法及进展](http://mp.weixin.qq.com/s/cDq1vwMig2V0lJrswP3gcA)
- [排序方法比较大全PCA、PCoA、NMDS、CCA](http://mp.weixin.qq.com/s/juMOVzZfdUD4w9M2l1Bh6g)
- [LEfSe分析，你真的懂了么](http://mp.weixin.qq.com/s/5K8OTMee6CwDZz51YWJEDg)
- [宏基因组基础知识梳理](http://mp.weixin.qq.com/s/d-cmrrnFlI8gOBQtKLHxWw)
- 扩增子SCI套路[1微群落结构差异](http://mp.weixin.qq.com/s/tRc4PBS-PZh6ghxX1nlNcw) [2组间差异分析](http://mp.weixin.qq.com/s/yI1KlyluNyoPM0DE5LOAfg) [3系统总结](http://mp.weixin.qq.com/s/V4VCrJU4cSSpof2QDoDKNQ)
- [环境因子关联分析——我应该选择CCA还是RDA分析？](http://mp.weixin.qq.com/s/8D4vlBIhyYg0ZHtsdGn_kA)
- [“P值”背后那些不可不知的事儿](http://mp.weixin.qq.com/s/lKkvJ7s8dshe7mvDOnl6_w)
- [Adonis和ANOSIM方法组间整体差异评估原理](http://mp.weixin.qq.com/s/b2kjedvI-8hYSkTQxKUalA)
- [轻松看懂机器学习十大常用算法](http://mp.weixin.qq.com/s/sU__UxDDmhs-4pMGX-5rSQ)
- [一文读懂“随机森林”在微生态中的应用](http://mp.weixin.qq.com/s/58VAF03uO3nBPfp7eboqUA)
- [你想知道的“ROC曲线”](http://mp.weixin.qq.com/s/wRISqBabnFrtWD4TrCgBOg)
- [人体对微生物的管控](https://mp.weixin.qq.com/s/DYykdQ8DtBRIG7rzEK9Xug)
- [简单读懂微生物基因组的泛基因组学](http://mp.weixin.qq.com/s/p7PMqo2Ld0Kbm8_3IgRuuQ)

### 必读综述

- [Nature：宏基因组关联分析](http://mp.weixin.qq.com/s/CcDuohwezquBRhBW3FvMSg)
- [Nature：肠道菌群如何划分肠型](http://mp.weixin.qq.com/s/K3t7BpJ3LZvi4RNf69cJeA)
- [Nature: 来自细菌的通告——群感效应简介](http://mp.weixin.qq.com/s/8ltHVYeYksKLCs70FUctpg)
- [Nature：呼吸道菌群—呼吸道健康的守门人](http://mp.weixin.qq.com/s/DBYuQh4Pz2ZNpFXW71dD_Q)
- [Nature: 拥抱未知-解析土壤微生物组的复杂性](http://mp.weixin.qq.com/s/Ff1s8SzMkfHKmM2vbcI7mw)
- [Cell：代谢控制中的脑肠轴](http://mp.weixin.qq.com/s/cwElaRsaInfabuz0VF60gA)
- [研究微生物，只靠多组学根本不够](http://mp.weixin.qq.com/s/OuK8frQaXPUoeFqXazkEgw)  
- [中国微生物组计划—农作物微生物组](https://mp.weixin.qq.com/s/Ssy1Rq8bWrBzymWI-Xslmw)  
- [Annu Rev：植物微生物组—系统见解与展望](https://mp.weixin.qq.com/s/rx2ae4BcXqqkeX5LDi0h-Q)  
- [Annual Reviews|微生物组与人](http://mp.weixin.qq.com/s/DVJSY3zKKI3IDV9vW3khJw)
- [微生物组学与植物病害微生物防治](https://mp.weixin.qq.com/s/Bba4ddqyvj2C0Mdx6cUm8A)  
- [组学重建真菌现有分类系统](https://mp.weixin.qq.com/s/qpK28hjqvtPSCKKB9lWtYg)  
- [微生物应用|农业废弃物资源化利用](http://mp.weixin.qq.com/s/zCk85qBaY5u5IHHHr99NNQ)  
- 宏基因组学入门[1初识](http://mp.weixin.qq.com/s/xVJtplV6LLofrt5DKqA9vA)  [2进一步](http://mp.weixin.qq.com/s/Otz6Kk_g4N_pu5vHWaJCfA)  [3拼接](http://mp.weixin.qq.com/s/a1b-4bdjushFn1PqJ6NU2Q)  
- [肠道微生物与人类密切相关的方方面面](http://mp.weixin.qq.com/s/KposoZo9X1TYxRCHYlLbtw)
- [Nature: 测序技术的前世今生](http://mp.weixin.qq.com/s/H-LF6dax0uYeJ-H1gDwycQ)
- [Nature Reviews：全新的益生元定义和范围](http://mp.weixin.qq.com/s/hMImkvaugXD6Jkv9i0SvTQ)
- [原核转录组非编码RNA研究](http://mp.weixin.qq.com/s/MwEHXbPdpkKO5tuNKjqI8Q)

### 高分文章套路解读

- [Nature: 培养组学—高通量细菌分离培养鉴定](http://mp.weixin.qq.com/s/_xaxicmV5cyKfnYoKHQQbg) 
- [SR: 真菌培养组学同揭示人类肠道真菌群落结构](https://mp.weixin.qq.com/s/_DjxjlXH3URKpZN50zPqWQ)
- [Nature: 地球微生物组计划首发成果—揭示地球多尺度微生物多样性](http://mp.weixin.qq.com/s/q9Tqbd8VITkYtZIFbByLtg)
- [Nature：如何做一篇肠道菌群免疫的顶级文章](http://mp.weixin.qq.com/s/tiBLevKw9HNAW9I0A_Of8A)
- [Nat Biotech: 宏表观组—DNA甲基化辅助宏基因组binning](http://mp.weixin.qq.com/s/j9HolFL4bqbjcLHrp4OJAA)
- [Nature: 甘露糖苷选择性抑制致病性大肠杆菌](http://mp.weixin.qq.com/s/45L9UNx7eqkMxFbckoTEYQ)  
- [Nature: 拟南芥根微生物组的结构和组成](http://mp.weixin.qq.com/s/OlFgv-ttRnFdIGXxYjoisw)  
- [Nature: 地球上最古老的热液喷口发现早期生命迹象](http://mp.weixin.qq.com/s/uth0BFcvAePl4dSGzv-psQ)
- [Nature Method: 宏基因组软件评估—人工重组宏基因组基准数据集](http://mp.weixin.qq.com/s/kDYiFfJ8egosETwLpKCFLQ)   
- [Nature Genetics：微生物基因组如何适应植物？(news & views)](http://mp.weixin.qq.com/s/rYyeVFp_ss9lITCytc9LUw)
- [NC：降低微生物群落复杂度突破组装难题](http://mp.weixin.qq.com/s/K8PwcuyWs3gnUEGwYEMceA)  
- [NC：自体免疫水泡皮肤病中鉴定基因与微生物组互作](https://mp.weixin.qq.com/s/kZ-_TsNcsrLJPaxqUex0Cg)  
- [GigaScience:植物MWAS研究—谷子产量与微生物组关联分析](http://mp.weixin.qq.com/s/TNCos80soqLAbhxHptRUhA)  
- [Microbiome：微生物组研究中你必须注意的细节](http://mp.weixin.qq.com/s/m1znPpGR6NbewL2AtJkKPw)  
- [Microbiome：HiSeq平台16S扩增子文库构建方法](http://mp.weixin.qq.com/s/E1qMskVQ64y6MKE8zDvNmQ)  
- [Microbiome: 简单套路发高分文章--杨树微生物组](http://mp.weixin.qq.com/s/Zod4Ca1tk3y5lIdI6RCiQQ)  
- [Microbiome：肠道菌群失衡促进高血压](http://mp.weixin.qq.com/s/n5u-Vm5e53x7XcxwYDbTRQ)  
- [Microbiome：重新定义“卫生”概念](http://mp.weixin.qq.com/s/jiQsN3sPgbJcdVa-SuSvGQ)
- [ME：网络分析揭示微生物群落应对环境扰动的稳定性机制](http://mp.weixin.qq.com/s/649mjxr62v9RHp3AGWLzpg)
- [SR: 土壤细菌定量方法结合相对丰度分析揭示种群的真实变化](http://mp.weixin.qq.com/s/ipBhAagpEPn1EIKXDUlGRw)

### 科普视频-寓教于乐

- [BBC人体奥秘之细胞的暗战](http://mp.weixin.qq.com/s/M35ebWAelDIK5Iqib06JzA)
- [BBC人体奥秘 Inside.the.Human.Body](https://mp.weixin.qq.com/s/xlCdN8il1hcutkYK-42fAQ)
- [NG人体内旅行Inside.the.Living.Body](http://mp.weixin.qq.com/s/xqgolgPlRDYQDkDiWu8zOA)
- [NG子宫日记 Womb](http://mp.weixin.qq.com/s/XZ5yNW56Bf4NFkcbuxgQYw)  
- [NHK: 再造人类生命的神奇细胞](https://mp.weixin.qq.com/s/IHN4O5xk6ySV5EC8QpBjDw)
- [CCTV9让尸体说话-法医密档](http://mp.weixin.qq.com/s/sHTTd_Rb7XibV4CoCVzcAQ)
- [豆瓣8.9，惹哭亿万中国人的纪录片-本草中华](http://mp.weixin.qq.com/s/nR2EiQYcEYH3VeR3RDlT5w)
- [2分钟视频回顾植物学家钟扬的贡献](http://mp.weixin.qq.com/s/qul0uhcLY3xS4Dyxbd7GaA)
- [一顿“寄生虫大餐”，或能治好干净引来的免疫病](https://mp.weixin.qq.com/s/hX0K9TOLPnrZ6f8lUoSYag)
- [只要11天，浓度1000倍的抗生素也无效——超级细菌](http://mp.weixin.qq.com/s/SXmXlu7XFnO9fIgejSWdtA)
- [致命病毒为何疯狂袭击人类？都怪我们那群会飞的远房亲戚](http://mp.weixin.qq.com/s/CAh-hYRCfvQbyDeh6xlyYA)
- [土豆上的小霉菌引发百万人死亡和逃难，却造就全球7千万后裔](http://mp.weixin.qq.com/s/jv2ZKWqDTB_IyLeMImHvDw)
- [看完这些能控制大脑的寄生虫，你会怀疑人类！](http://mp.weixin.qq.com/s/P2od51617RZGxrmLBMSKZw)
- [梅毒狂想曲](http://mp.weixin.qq.com/s/XfeuKLLg3ruXUCFnFAisog)

### 友军文章汇总推荐

- [学习生信的系列教程](https://mp.weixin.qq.com/s/VguRtaGpEcaNzmZEi48gLg)——纯生信一作发IF>20的大神

